language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "uVDtsBmgbgN43yaAVgsisryfRHGUK6J5mpqjiGYZN0WhbOe60SwwxDZBgDMfFSfk6bVr2oL8E4B0gWRKN4v1qwrDPrQIP8JZgDwubxyCme+959GVZZMQUHnkp3pquZyf4xnfPgDGX+sxqZcikZgzCPMDbZVGFborwPPYHw/vNi76VK0RG9eTqWZQBPTTRU+FonAuqpJrURzTdgl2qDwiC1GQXUQSuAUlvmZ88pbSPryzGz/r6cdi60Gkk8nXzv4z9f3TMEyxxMc3CH7F4AHyUeR0u3H5kseKsJf+16mRheDWXYLJK+qe12243MbQu6IrlSkqQOhGy2F9fUYb3HJzbhf147osmpVyEXwxDTr7xmXmIO/JCRDzY4hB1tx9/uhrEho8LqOY51W3C9yIGvJ7De/X+YjJow4sr2y+W0f23Aw2GlTFRnisogLvroMdv+FUys/Ssa5UQt8+lUKDXZd6rbOYXWAeNXADFRAeb1YQgZ0zQLq3ppvA7vayo/rH7MKznbsOy4BlSD2/Tade4eduHaOMNcthb54AA9S3QUN+YFzjRZHT5rCNKv8gIv/9QCItQNhRpxrXu1KjnZRJogu30rpCDVBBqLlJxyQO26yWI8d6NHaTYFSYNIEFcDdxfcgcr05jV3W6irbHYcb/qrKm1urXA3ik4aWQg67AsfYUSdg="
  app: image-upload-spring
