language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "0HGs/n81OhfW+5j7p08q+PBwVft6D9OwXSzknheZGPUzvufe5IhxSzRbOB2CVNoUZU+p0rDPAzrFZWv9oQyy87ZOGiGhIQYNr6G1OaVgWPwEmS6mnXEjWZsNTzTl0G0C0+RXf4RsgP8M2j3FsLH1CbYUeEAT6LS78CI6jdCQssh0w6A/C9i2fQe2t+8XmP0SVOfc5x642tttPz3qlQjs43DHGVVQc1FgGjaNNAuTHeFUcMOlzzRwHahL6UVwGEUiAnypS3gfTIUGbGALtXGeQlWU3Y89rS/aV0ZUEQ9Jxs3vhNzbqz4qxW718pYFLGCVYKg2j/McQJ0H9RvDDEYfCtxiy9aS372jaiOzb+2LLP9lJyvimcYNSyFNNjAAnewqSeg+6662a1hYe+ZOJs6SO26YZtzPYX6mKj/oo5rBHfkbCQ1JMmThC1m7TO405vVa12P8kWPIiqTY95wulWr1Rmv7v5RSn0XAw6ifSZw1T5GuuA/I2/vuybvJvj/vq3PaPwQyblucIz5bM/XJdFrHEea/psXYEaEPieRWha6wHmTLktXG82C9LVYYDP57ZSBe6EljmMfUGxNBaWqMm5/R2ie5lGyXHi4+Pts4F4edBZmRbCl0389EPRarMsbxAh8cKn7yLPQsCDGoubaI5hHhL8vO6dEy7P7ZuD4bw8lkqMU="
  app: image-upload-spring
