language: java
jdk: oraclejdk8

deploy:
  provider: heroku
  api_key:
    secure: "li+rdd1C4f3MLb8VHwOdNJo86uJh3i8BRe8A28zLC7UjM/UhA83bsSVaQSlFZj65viMB3fd4SRKPxNQlwbig+DjAypgKy4sw/w4qpAnrh6E8urOcaI9APCtqtK4VZ0Nsmb2gZTipRaWt5BOv/Gk1ZG1nfRQ/LfevWLZ27PjoLO2wpRmNcF9KFioGTBPHGO2bpI3M68/kGVNTyhXil6s8QYrszhMnF6g4glgmeGgBAvr3Mj3gzORFnNfbZu/WCPADtZwXU6/DYxDhRkoYTxufP6bhEINGI+0HIrrUgx0M8Avqi2q5qIz9uX/p0jw59psxc6jPmdmg5xLycmO9GhfFtkep2J2jzrcXSyP7EZEmuQS19dHZuPOenY3AyKEWWvQSaUbdWigMbqE/aKtxQ3yHt9v/eKo6L+OCwshd4NuPFppN/DqrY/Q7GdXVQUSKarvXFbCJmvLTNwPM6MiqlnsO4dEF3PG8fl4p7/VlcsqjBoXk0VjUXsgttDAfsGhKP5eLyZ2lUyN49pvtOk5t1wCjRheaDPvP3wRSx10iLC78XIUKZfaFvEnhb28uflYxhHL3YP+yCltJlwpYWSCpbTTMkXeb0qjTB368vGVEYuvPzOFhwfFykI6G4EW9WXk184T72BA4+FypL3elosYkuYVmiRQg8UhllDuCiOtoCPhdXUU="
  app: image-upload-spring
